stages:
  - build
  - deploy

build:
  stage: build
  image: node:12

  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
      - .npm/

  before_script:
    - npm ci --cache .npm --prefer-offline

  script:
    - npm run lint
    - npm run build

  artifacts:
    paths:
      - dist

deploy:
  stage: deploy
  image: alpine
  only:
    - release
  before_script:
    # SSH and rsync Setup
    - apk add --update --no-cache openssh rsync

    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - rsync --rsh ssh --recursive --delete dist cron-push@cronpush.tygr.info:cron-push
