---
os: linux
dist: xenial
language: node_js
node_js: lts/*

addons:
  ssh_known_hosts: cronpush.tygr.info
  chrome: stable

# SSH Setup
before_script:
  - openssl aes-256-cbc
    -K $encrypted_db2095f63ba3_key
    -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc
    -out /tmp/deploy_rsa
    -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

jobs:
  include:
    - stage: test
      script: npm run lint
    - script:
        - npm run build
        - npm test
      # Always deploy reports
      after_script: bash scripts/report-deploy.sh
      deploy:
        edge: true
        # Only release on main branch
        on:
          branch: main
        provider: script
        script: bash scripts/web-deploy.sh
